export const walkthroughSteps = [
  {
    id: "welcome",
    title: "Welcome to HealthInsight! 🎉",
    content: "Your AI-powered healthcare intelligence platform built for analysts and investors. This quick 5-step tour will show you the key features that accelerate your research and deal preparation.",
    placement: "center",
    page: null,
  },
  {
    id: "dashboard",
    title: "Step 1 — Dashboard: Your Intelligence Command Center",
    content: "The Dashboard aggregates the latest healthcare market movements in one place.\n\n• 📊 Top-level stats: newsletters analyzed, M&A deals tracked, funding rounds, and key themes\n• 📈 Trend charts showing activity over time by sector\n• 🗂 Filter by source, topic, date range, and sentiment to zero in on what matters\n• 🔍 Each newsletter card shows TLDR summaries, key statistics, and recommended actions\n\nStart here every morning to catch up on overnight intelligence.",
    placement: "center",
    page: "Dashboard",
  },
  {
    id: "knowledge-hub",
    title: "Step 2 — Knowledge Hub: Find Your Therapeutic Area",
    content: "The Knowledge Hub is where you discover emerging themes and track specific companies.\n\n• 🧬 Browse Emerging Themes — AI-identified topics trending across all analyzed newsletters\n• 🏢 Key Players — companies ranked by newsletter mention frequency\n• Click any theme or company to open a dedicated page with full timeline, AI briefings, and deep-dive research\n• Use the Topics Directory to follow niche therapeutic areas like Behavioral Health, ASC, or Imaging\n\nUse this to build conviction on a sector before a call or deal review.",
    placement: "center",
    page: "KnowledgeHub",
  },
  {
    id: "pe-meeting-prep",
    title: "Step 3 — PE Meeting Prep: Generate Prep Materials in Minutes",
    content: "Purpose-built for healthcare services and HCIT deal preparation.\n\n• 📋 Enter a counterparty name, website URL, and sector tags\n• 🎯 Select your role (PE Sponsor, Investment Bank, Lender, etc.) and meeting context\n• 🤖 The AI agent pulls internal newsletter intelligence + live web research to generate a structured 1-page brief covering: business model, market position, recent M&A, key questions, and risks\n• 📁 Briefs are saved to your history for easy reference before future meetings\n\nTypically takes 60–90 seconds to generate a board-ready brief.",
    placement: "center",
    page: "PEMeetingPrep",
  },
  {
    id: "my-library",
    title: "Step 4 — My Library: Your Saved Insights & Watched Topics",
    content: "My Library is your personal research hub — everything you've saved lives here.\n\n• 🔖 Saved Summaries: AI briefings you've generated and saved for later reference\n• 🔍 Saved Searches: re-run any past search with one click\n• 👁 Watched Topics: topics you follow, with unread alert counts when new content arrives\n• 📊 Library Insights: an AI narrative of your recent activity patterns and top focus areas\n\nWatched topics are especially useful for staying on top of fast-moving sectors between deal cycles.",
    placement: "center",
    page: "MyLibrary",
  },
  {
    id: "user-settings",
    title: "Step 5 — User Settings: Configure Your Experience",
    content: "Tailor HealthInsight to your role and workflow.\n\n• 🏠 Default Landing Page: choose which page loads on login (Dashboard, Knowledge Hub, etc.)\n• 📅 Default Date Range: set how far back filters start (7d, 30d, 90d, YTD)\n• 🔔 Notifications: enable in-app or email alerts for watched topics\n• ⏱ Alert Frequency: immediate, daily digest, or weekly rollup\n• ✍️ AI Output Verbosity: concise, standard, or detailed summaries\n• 🎨 Preferred Sources & Topics: pre-filter the platform to your coverage universe\n\nTaking 2 minutes to configure this dramatically improves your day-to-day experience.",
    placement: "center",
    page: "UserSettings",
  },
  {
    id: "completion",
    title: "You're Ready to Go! 🚀",
    content: "You now know the five pillars of HealthInsight:\n\n1. Dashboard — daily market intelligence\n2. Knowledge Hub — sector and company discovery\n3. PE Meeting Prep — AI-generated deal briefs\n4. My Library — saved insights and topic alerts\n5. User Settings — personalized to your role\n\nStart with the Dashboard to see what's happening in healthcare today. Click 'Start Tutorial' in the sidebar anytime to replay this tour.",
    placement: "center",
    page: null,
  },
];