export const walkthroughSteps = [
  {
    id: "welcome",
    title: "Welcome to HealthInsight! 🎉",
    content: "Your AI-powered healthcare intelligence platform built for analysts and investors. This quick 5-step tour will show you the key features that accelerate your research and deal preparation.",
    placement: "center",
    page: null,
  },
  {
    id: "dashboard",
    title: "Step 1 — Dashboard: Your Intelligence Command Center",
    content: "The Dashboard aggregates the latest healthcare market movements in one place.\n\n• 📊 Top-level stats: newsletters analyzed, M&A deals tracked, funding rounds, and key themes\n• 📈 Trend charts showing activity over time by sector\n• 🗂 Filter by source, topic, date range, and sentiment to zero in on what matters\n• 🔍 Each newsletter card shows TLDR summaries, key statistics, and recommended actions\n\nStart here every morning to catch up on overnight intelligence.",
    placement: "center",
    page: "Dashboard",
  },
  {
    id: "knowledge-hub",
    title: "Step 2 — Knowledge Hub: Find Your Therapeutic Area",
    content: "The Knowledge Hub is where you discover emerging themes and track specific companies.\n\n• 🧬 Browse Emerging Themes — AI-identified topics trending across all analyzed newsletters\n• 🏢 Key Players — companies ranked by newsletter mention frequency\n• Click any theme or company to open a dedicated page with full timeline, AI briefings, and deep-dive research\n• Use the Topics Directory to follow niche therapeutic areas like Behavioral Health, ASC, or Imaging\n\nUse this to build conviction on a sector before a call or deal review.",
    placement: "center",
    page: "KnowledgeHub",
  },
  {
    id: "pe-meeting-prep",
    title: "Step 3 — PE Meeting Prep: Generate Prep Materials in Minutes",
    content: "Purpose-built for healthcare services and HCIT deal preparation.\n\n• 📋 Enter a counterparty name, website URL, and sector tags\n• 🎯 Select your role (PE Sponsor, Investment Bank, Lender, etc.) and meeting context\n• 🤖 The AI agent pulls internal newsletter intelligence + live web research to generate a structured 1-page brief covering: business model, market position, recent M&A, key questions, and risks\n• 📁 Briefs are saved to your history for easy reference before future meetings\n\nTypically takes 60–90 seconds to generate a board-ready brief.",
    placement: "center",
    page: "PEMeetingPrep",
  },
  {
    id: "my-library",
    title: "Step 4 — My Library: Your Saved Insights & Watched Topics",
    content: "My Library is your personal research hub — everything you've saved lives here.\n\n• 🔖 Saved Summaries: AI briefings you've generated and saved for later reference\n• 🔍 Saved Searches: re-run any past search with one click\n• 👁 Watched Topics: topics you follow, with unread alert counts when new content arrives\n• 📊 Library Insights: an AI narrative of your recent activity patterns and top focus areas\n\nWatched topics are especially useful for staying on top of fast-moving sectors between deal cycles.",
    placement: "center",
    page: "MyLibrary",
  },
  {
    id: "user-settings",
    title: "Step 5 — User Settings: Configure Your Experience",
    content: "Tailor HealthInsight to your role and workflow.\n\n• 🏠 Default Landing Page: choose which page loads on login (Dashboard, Knowledge Hub, etc.)\n• 📅 Default Date Range: set how far back filters start (7d, 30d, 90d, YTD)\n• 🔔 Notifications: enable in-app or email alerts for watched topics\n• ⏱ Alert Frequency: immediate, daily digest, or weekly rollup\n• ✍️ AI Output Verbosity: concise, standard, or detailed summaries\n• 🎨 Preferred Sources & Topics: pre-filter the platform to your coverage universe\n\nTaking 2 minutes to configure this dramatically improves your day-to-day experience.",
    placement: "center",
    page: "UserSettings",
  },
  {
    id: "completion",
    title: "You're Ready to Go! 🚀",
    content: "You now know the five pillars of HealthInsight:\n\n1. Dashboard — daily market intelligence\n2. Knowledge Hub — sector and company discovery\n3. PE Meeting Prep — AI-generated deal briefs\n4. My Library — saved insights and topic alerts\n5. User Settings — personalized to your role\n\nStart with the Dashboard to see what's happening in healthcare today. Click 'Start Tutorial' in the sidebar anytime to replay this tour.",
    placement: "center",
    page: null,
  },
];
    title: "Welcome to HealthInsight! 🎉",
    content: "Your AI-powered healthcare intelligence platform. Let's take a quick tour of the key features that will help you stay informed and make better strategic decisions.",
    placement: "center",
    page: null,
  },
  {
    id: "knowledge-hub",
    title: "Knowledge Hub - Your Starting Point",
    content: "This is your command center. From here, you can access featured topics, browse sources, and pick up where you left off. Think of it as your personalized homepage.",
    placement: "center",
    page: "KnowledgeHub",
    highlightSelector: null,
  },
  {
    id: "explore-all-sources",
    title: "Explore All Sources",
    content: "Search and filter across all newsletter content. Use keywords, date ranges, and topic filters to find exactly what you need. Select items to generate AI summaries.",
    placement: "center",
    page: "ExploreAllSources",
  },
  {
    id: "search-filters",
    title: "Powerful Search & Filters",
    content: "Filter by date range, sources, and topics. Add custom topics to track emerging themes. Your searches are automatically logged to build your Library Insights.",
    placement: "right",
    page: "ExploreAllSources",
  },
  {
    id: "summary-builder",
    title: "AI Summary Builder",
    content: "Select newsletters and click 'Generate Summary' to create structured briefings. Our AI agents analyze content and synthesize key themes, trends, and insights—perfect for strategy meetings.",
    placement: "left",
    page: "ExploreAllSources",
  },
  {
    id: "learning-packs",
    title: "Learning Packs",
    content: "Curated topic bundles with pre-configured searches. Each pack covers a specific healthcare domain (Value-Based Care, AI in Healthcare, etc.) and instantly filters content to relevant items.",
    placement: "center",
    page: "LearningPacks",
  },
  {
    id: "pack-summaries",
    title: "Pack-Level Summaries",
    content: "Open any Learning Pack to view all matching content, then generate a comprehensive Pack Summary. These summaries identify key drivers, trends, and implications for operators, payors, and investors.",
    placement: "center",
    page: "LearningPacks",
  },
  {
    id: "custom-packs",
    title: "Create Custom Packs",
    content: "Build your own intelligence packs by adding items from any search results. Add notes to each item, organize by priority, and generate summaries tailored to your research needs.",
    placement: "center",
    page: "MyCustomPacks",
  },
  {
    id: "my-library",
    title: "My Library - Your Personal Hub",
    content: "Your activity, favorites, saved searches, and summaries all in one place. This is where your research history lives and where you can quickly access your most-used resources.",
    placement: "center",
    page: "MyLibrary",
  },
  {
    id: "library-insights",
    title: "My Library Insights",
    content: "See what you've been focusing on: top topics, most-opened packs, source preferences, and activity stats. Generate an AI narrative that describes your recent learning patterns.",
    placement: "center",
    page: "MyLibrary",
  },
  {
    id: "watch-topics",
    title: "Watch Topics & Alerts",
    content: "Follow specific topics to get notified when new content arrives. Your watched topics appear in My Library with unread counts and recent updates.",
    placement: "center",
    page: "MyLibrary",
  },
  {
    id: "topic-pages",
    title: "Topic Pages",
    content: "Deep-dive into any healthcare topic. Get Smart Fast with a 60-second AI briefing, or generate a comprehensive Deep Dive research packet with timelines, landscapes, and major news.",
    placement: "center",
    page: "TopicsDirectory",
  },
  {
    id: "company-pages",
    title: "Company Pages",
    content: "Track specific companies across all content. View timelines of mentions, M&A activity, funding rounds, and AI-generated company overviews based on newsletter coverage.",
    placement: "center",
    page: "CompaniesDirectory",
  },
  {
    id: "pe-meeting-prep",
    title: "PE Meeting Prep",
    content: "Generate PE-grade Initial Meeting Briefs for companies, sponsors, or counterparties. Enter a company name and URL, add sector tags, and our specialized AI agent creates a concise 1-page brief covering business model, market position, recent transactions, key questions, and risks—tailored for healthcare services and HCIT deals.",
    placement: "center",
    page: "PEMeetingPrep",
  },
  {
    id: "ai-agents",
    title: "AI Agents Powering Your Intelligence",
    content: "Behind the scenes, specialized AI agents handle different tasks:\n\n• SummaryAgent - General briefings\n• PackSummaryAgent - Learning Pack synthesis\n• GetSmartFastAgent - Quick topic briefings\n• DeepDiveAgent - Comprehensive research reports\n• MarkdownFormatterAgent - Clean exports\n• InsightsNarrativeAgent - Activity summaries\n• PE Meeting Brief Agent - Deal preparation briefs\n\nEach agent is optimized for its specific task.",
    placement: "center",
    page: null,
  },
  {
    id: "ai-defense",
    title: "AI Safety & Security",
    content: "All AI calls go through a global Prompt Injection Defense Layer that:\n\n• Treats all content as data, not instructions\n• Prevents malicious prompt manipulation\n• Ensures consistent, safe outputs\n• Maintains professional tone and structure\n\nThis keeps your summaries reliable and secure, even if source content contains embedded instructions.",
    placement: "center",
    page: null,
  },
  {
    id: "completion",
    title: "You're All Set! 🚀",
    content: "You now know how to explore sources, use Learning Packs, build custom intelligence collections, track topics, and leverage AI agents for strategic insights. Start exploring and let HealthInsight accelerate your healthcare intelligence research!",
    placement: "center",
    page: null,
  },
];